### ISSUE TITLE
fix-EB benchmark with 0 iterations causes segmentation fault

### ISSUE THREAD

**Issue by mreineck** [yzgd/fastSHT#4]
I'm trying to run `benchmark.py` in `fix-eb` mode with zero iterations,and this leads to a segmentation fault:

```
martin@marvin:~/codes/fastSHT$ PYTHONPATH=/home/martin/codes/fastSHT/:/home/martin/codes/fastSHT/obj/ LD_LIBRARY_PATH=/opt/intel/oneapi/mkl/2022.1.0/lib/intel64/:/opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/:/opt/intel/oneapi/mkl/2022.1.0/lib/intel64/:/home/martin/codes/fastSHT/obj python3 scripts/benchmark.py 32 1000 8 0 fix-eb true
 
Working with the following parameters:
Nside = 32, Nsim = 1000, n_proc = 8, Niter = 0, comparison with HEALPix = True, test type=fix-eb
Note: this test will only show the time cost. For accuracies use test_comprehensive.py
 
Testing fix_EB...
Segmentation fault
```

Is this a known/expected problem?

**Comment by ctian282** [comment]
Thank you for pointing this out. It is a bug due to that we wanted to save some memory by not allocating some buffer arrays when `niter=0`. But in `fix_eb`, even if niter=0, we still need those buffers that are not properly allocated to finish this job. So we have now added a new argument `all_buff` to `__init__` to force allocating all buffer arrays when necessary.  This new `all_buff` is now set to `True` in the `fix_eb` function in `benchmark.py` and should have fixed this problem.

**Comment by mreineck** [comment]
Thank you!
